version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=mysqlpassword
      - MYSQL_DATABASE=backend_db
      - FRONTEND_URL=http://localhost:5173,https://frontend-prod.example.com,https://frontend-staging.example.com
    volumes:
      - ./src:/app/src
      - ./key.pem:/app/key.pem
      - ./cert.pem:/app/cert.pem
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "npm run migration:run && npm run start"
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpassword
      - MYSQL_DATABASE=backend_db
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data: